package com.guiado.akbhar.model

enum class MagazineCategoryEnum {
    GENERAL, WOMEN, NEWS, TECHNOLOGY, SPORTS, BUSINESS, DESIGN, PHOTOGRAPHY, ART_AND_CULTURE, POLITICS, STYLE, MUSIC, GAMING, YOGA, HEALTH, BANKING, SCIENCE, FASHION
}